version: '3.8'
services:
    app:
        build:
            args:
                user: lequanphat
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
        networks:
            - mynetwork
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - 8005:80
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - mynetwork
    db:
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: furniture_shop
            MYSQL_ROOT_PASSWORD: mysql12345
            MYSQL_USER: lequanphat
            MYSQL_PASSWORD: mysql12345
        ports:
            - '9906:3306'
        volumes:
            - ./database/furniture_shop-database.sql:/docker-entrypoint-initdb.d/dump.sql
        networks:
            - mynetwork

#Docker Networks
networks:
    mynetwork:
        driver: bridge
